const fenceData = {
    materials: {
        posts: {
            'post_4x4x8_pt': { price: 9.88, description: '4"x4"x8\' PT Post', itemNumber: '552328' },
            'post_4x4x10_pt': { price: 15.78, description: '4"x4"x10\' PT Post', itemNumber: '312624' },
            'post_6x6x8_pt': { price: 32.98, description: '6"x6"x8\' PT Post', itemNumber: '313302' },
            'post_6x6x10_pt': { price: 43.58, description: '6"x6"x10\' PT Post', itemNumber: '313813' },
            'post_5x5x8_vinyl': { price: 44.73, description: '5"x5"x8\' Vinyl Line Post', itemNumber: '758812' },
            'post_5x5x8_vinyl_corner': { price: 44.73, description: '5"x5"x8\' Vinyl Corner Post', itemNumber: '758813' },
            'post_5x5x8_vinyl_end': { price: 44.73, description: '5"x5"x8\' Vinyl End Post', itemNumber: '758814' },
            'post_5x5x5_vinyl_2rail': { price: 40.20, description: '5"x5"x5\' Vinyl 2rail Ranch Line Post', itemNumber: '202869518' },
            'post_5x5x5_vinyl_2rail_end': { price: 38.12, description: '5"x5"x5\' Vinyl 2rail Ranch End Post', itemNumber: '202869519' },
            'post_5x5x5_vinyl_2rail_corner': { price: 31.67, description: '5"x5"x5\' Vinyl 2rail Ranch Corner Post', itemNumber: '202869520' },
            'post_5x5x7_vinyl_3rail': { price: 44.53, description: '5"x5"x7\' Vinyl 3rail Ranch Line Post', itemNumber: '100033704' },
            'post_5x5x7_vinyl_3rail_corner': { price: 46.62, description: '5"x5"x7\' Vinyl 3rail Ranch Corner Post', itemNumber: '100007622' },
            'post_5x5x7_vinyl_3rail_end': { price: 39.74, description: '5"x5"x7\' Vinyl 3rail Ranch End Post', itemNumber: '100006178' },
            'post_cedar_2rail': { price: 18.68, description: '4"x4"x5-1/3\' Cedar Line Post', itemNumber: '140392' },
            'post_cedar_2rail_end': { price: 17.58, description: '4"x4"x5-1/3\' Cedar End Post', itemNumber: '198605' },
            'post_cedar_2rail_corner': { price: 18.68, description: '4"x4"x5-1/3\' Cedar Corner Post', itemNumber: '198606' },
            'post_cedar_3rail': { price: 35, description: '4"x4"x5-1/3\' Cedar 3rail Line Post', itemNumber: '3railline' },
            'post_cedar_3rail_end': { price: 35, description: '4"x4"x5-1/3\' Cedar 3rail End Post', itemNumber: '3railline' },
            'post_cedar_3rail_corner': { price: 35, description: '4"x4"x5-1/3\' Cedar 3rail Corner Post', itemNumber: '3railline' },
            'post_aluminum_line': { price: 28.98, description: '7\' Black Aluminum Line Post', itemNumber: '418557' },
            'post_aluminum_corner': { price: 28.98, description: '7\' Black Aluminum Corner Post', itemNumber: '418004' },
            'post_aluminum_end': { price: 30.48, description: '7\' Black Aluminum End Post', itemNumber: '418559' }
        },
        pickets: {
            'picket_5_8x6_de': { price: 2.08, description: '5/8"x6\' DE Picket', itemNumber: '202922', coverage: 0.458 },
            'picket_5_8x8_de': { price: 3.98, description: '5/8"x8\' DE Picket', itemNumber: '99649', coverage: 0.458 },
            'picket_5_8x6_cedar': { price: 3.78, description: '5/8"x6\' DE Cedar Picket', itemNumber: '873343', coverage: 0.458 },
            'picket_3_4x4_gothic': { price: 2.48, description: '3/4"x4\' Gothic Picket', itemNumber: '156667', coverage: 0.291 }
        },
        rails: {
            'rail_2x4x16': { price: 11.38, description: '2"x4"x16\' Rail', itemNumber: '197672' },
            'rail_2x6x16': { price: 15.18, description: '2"x6"x16\' Rail', itemNumber: '239853' },
            'rail_cedar_2rail': { price: 15.38, description: '10\' Cedar Split Rail', itemNumber: '14581' },
            'rail_cedar_3rail': { price: 25, description: '10\' Cedar Split Rail 3rail', itemNumber: '3railRail' },
            'rail_vinyl_8': { price: 27.56, description: '8\' Vinyl Ranch Rail', itemNumber: '203008796' }
        },
        panels: {
            'panel_cattle_5x16': { price: 119.99, description: '5\'x16\' Cattle Panel', itemNumber: '3610375', coverage: 15 },
            'panel_hogwire_4x50': { price: 86.98, description: '4\'x50\' Black Hogwire Roll', itemNumber: '44296', coverage: 45 },
            'panel_hogwire_6x50': { price: 99.00, description: '6\'x50\' Black Hogwire Roll', itemNumber: '495517', coverage: 45 },
            'panel_aluminum_4_5': { price: 82.98, description: '4.5\' Black Aluminum Fence Panel', itemNumber: '418560', coverage: 6 },
            'panel_vinyl_6x8': { price: 99.00, description: '6\'x8\' Vinyl Panel', itemNumber: '12092', coverage: 8 }
        },
        concrete: {
            'concrete_50lb': { price: 4.15, description: '50# Concrete', itemNumber: '222710' },
            'concrete_80lb': { price: 6.98, description: '80# Concrete', itemNumber: '10385' },
            'concrete_50lb_fast': { price: 6.98, description: '50# Fast Set Concrete', itemNumber: '10437' }
        },
        caps: {
            'cap_2x2x8': { price: 4.98, description: '2"x2"x8\' Cap', itemNumber: '314397' },
            'cap_2x4x16': { price: 11.38, description: '2"x4"x16\' Cap', itemNumber: '197672' },
            'cap_2x6x16': { price: 15.18, description: '2"x6"x16\' Cap', itemNumber: '239853' }
        },
        trim: {
            'trim_1x2x8': { price: 2.78, description: '1"x2"x8\' Trim', itemNumber: '201999' },
            'trim_1x4x8': { price: 4.78, description: '1"x4"x8\' Trim', itemNumber: '314407' },
            'trim_1x4x12': { price: 7.18, description: '1"x4"x12\' Trim', itemNumber: '314409' },
            'trim_1x6x8': { price: 5.88, description: '1"x6"x8\' Trim', itemNumber: '314412' },
            'trim_1x6x12': { price: 8.98, description: '1"x6"x12\' Trim', itemNumber: '314414' }
        },
        postTops: {
            'top_4x4_metal': { price: 2.93, description: '4"x4" Post Metal Pyramid Top', itemNumber: '1005542501' },
            'top_6x6_metal': { price: 3.86, description: '6"x6" Post Metal Pyramid Top', itemNumber: '1005542504' },
            'top_4x4_copper': { price: 9.98, description: '4"x4" Post Copper Pyramid Top', itemNumber: '7633' },
            'top_6x6_copper': { price: 14.98, description: '6"x6" Post Copper Pyramid Top', itemNumber: '65588' },
            'top_5x5_vinyl': { price: 2.77, description: '5"x5" Vinyl Pyramid Top', itemNumber: '87410' },
            'top_5x5_vinyl_decorative': { price: 8.48, description: '5"x5" Vinyl Decorative Top', itemNumber: '44457' },
            'top_5x5_vinyl_ranch': { price: 3.92, description: '5"x5" Vinyl Ranch Pyramid Top', itemNumber: '205883723' }
        },
        gates: {
            'gate_3_aluminum': { price: 306.99, description: '3\' Black Aluminum Gate Panel', itemNumber: '670619' },
            'gate_4_aluminum': { price: 279.00, description: '4\' Black Aluminum Gate Panel', itemNumber: '418558' },
            'gate_4_aluminum_arch': { price: 446.35, description: '4\' Black Aluminum Arch Gate Panel', itemNumber: '384466' },
            'gate_3_vinyl': { price: 137.00, description: '3\' White Vinyl Gate Panel', itemNumber: '758803' },
            'gate_4_vinyl': { price: 137.00, description: '4\' White Vinyl Gate Panel', itemNumber: '758803' },
            'gate_5_vinyl': { price: 137.00, description: '5\' White Vinyl Gate Panel', itemNumber: '758803' },
            'gate_6_aluminum': { price: 385.39, description: '6\' Black Aluminum Gate Panel', itemNumber: '670628' }
        },
        hardware: {
            'hinge_strap': { price: 22.98, description: 'Gate Strap Hinges', itemNumber: '674916' },
            'latch_2way': { price: 17.98, description: 'Gate 2-way Latch', itemNumber: '22293' },
            'latch_gravity': { price: 5.78, description: 'Gate Gravity Latch', itemNumber: '674908' },
            'latch_pool': { price: 95.18, description: 'Gate Pool Latch', itemNumber: '1303503' },
            'hinge_self_closing': { price: 37.98, description: 'Gate Self-Closing Hinges Pack', itemNumber: '689564' },
            'latch_stockade': { price: 28.48, description: 'Gate Stockade Latch', itemNumber: '648932' },
            'drop_pin': { price: 19.88, description: 'Gate Drop Pin 18"', itemNumber: '4103316' },
            'pin_catch': { price: 9.31, description: '3/4"x8" Black Pipe Nipple Pin Catch', itemNumber: '12946' }
        },
        fasteners: {
            'nails_2inch': { price: 41.98, description: '2" 1k box picket nails', itemNumber: '43564' },
            'nails_3inch': { price: 154.00, description: '3" 4k box framing nails', itemNumber: '688894' },
            'screws_1inch': { price: 6.98, description: '1" Black Metal 50 box Screws', itemNumber: '755598' }
        }
    },
    styles: {
        '4_gothic_picket': {
            name: '4\' Gothic Picket',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_3_4x4_gothic',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 2,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],

        },
        '6_gothic_picket': {
            name: '6\' Gothic Picket',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_3_4x4_gothic',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_6_de': {
            name: '4\' 6" DE',
            height: 4.5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 2,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5_6_de': {
            name: '5\' 6" DE',
            height: 5.5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_6_de': {
            name: '6\' 6" DE',
            height: 6.5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '7_6_de': {
            name: '7\' 6" DE',
            height: 7.5,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_6_de': {
            name: '8\' 6" DE',
            height: 8.5,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_framed_cattle_panel': {
            name: '4\'H Framed Cattle Panel',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            panelType: 'panel_cattle_5x16',
            railType: 'rail_2x4x16',
            railCount: 2,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
            additionalMaterials: {
                'rail_2x2x8': 4
            }
        },
        '4_framed_hogwire': {
            name: '4\' Framed Hogwire',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            panelType: 'panel_hogwire_4x50',
            railType: 'rail_2x4x16',
            railCount: 2,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
            additionalMaterials: {
                'rail_2x2x8': 4
            }
        },
        '6_framed_hogwire': {
            name: '6\' Framed Hogwire',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            panelType: 'panel_hogwire_6x50',
            railType: 'rail_2x4x16',
            railCount: 2,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
            additionalMaterials: {
                'rail_2x2x8': 4
            }
        },
         '4_plain_privacy_flat': {
            name: '4\' Plain Privacy Flat Cut',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5_plain_privacy_flat': {
            name: '5\' Plain Privacy Flat Cut',
            height: 5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_plain_privacy': {
            name: '6\' Plain Privacy',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_plain_privacy_flat': {
            name: '6\' Plain Privacy Flat Cut',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '7_plain_privacy_flat': {
            name: '7\' Plain Privacy Flat Cut',
            height: 7,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_plain_privacy': {
            name: '8\' Plain Privacy',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_plain_privacy_flat': {
            name: '8\' Plain Privacy Flat Cut',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_double_privacy_flat': {
            name: '4\' Double Privacy Flat Cut',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isDouble: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5_double_privacy_flat': {
            name: '5\' Double Privacy Flat Cut',
            height: 5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isDouble: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_double_privacy_flat': {
            name: '6\' Double Privacy Flat Cut',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isDouble: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '7_double_privacy_flat': {
            name: '7\' Double Privacy Flat Cut',
            height: 7,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isDouble: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_double_privacy_flat': {
            name: '8\' Double Privacy Flat Cut',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isDouble: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_double_privacy': {
            name: '6\' Double Privacy',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isDouble: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_double_privacy': {
            name: '8\' Double Privacy',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isDouble: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_hillsboro': {
            name: '4\' Hillsboro',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x12',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5_hillsboro': {
            name: '5\' Hillsboro',
            height: 5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x12',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_hillsboro': {
            name: '6\' Hillsboro',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x12',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '7_hillsboro': {
            name: '7\' Hillsboro',
            height: 7,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x12',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_hillsboro': {
            name: '8\' Hillsboro',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x12',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_hampton': {
            name: '4\' Hampton',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5_hampton': {
            name: '5\' Hampton',
            height: 5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_hampton': {
            name: '6\' Hampton',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '7_hampton': {
            name: '7\' Hampton',
            height: 7,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_hampton': {
            name: '8\' Hampton',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 0,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_shadowbox_flat': {
            name: '4\' Shadowbox Flat Cut',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isShadowbox: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5_shadowbox_flat': {
            name: '5\' Shadowbox Flat Cut',
            height: 5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isShadowbox: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_shadowbox': {
            name: '6\' Shadowbox',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isShadowbox: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_shadowbox_flat': {
            name: '6\' Shadowbox Flat Cut',
            height: 6,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x6_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isShadowbox: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '7_shadowbox_flat': {
            name: '7\' Shadowbox Flat Cut',
            height: 7,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isShadowbox: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_shadowbox_flat': {
            name: '8\' Shadowbox Flat Cut',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isShadowbox: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '8_shadowbox': {
            name: '8\' Shadowbox',
            height: 8,
            postType: 'post_4x4x10_pt',
            postSpacing: 7.5,
            picketType: 'picket_5_8x8_de',
            picketSpacing: 2.5,
            railType: 'rail_2x4x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: true,
            allowsCap: true,
            isShadowbox: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_2rail_cedar': {
            name: '4\' 2-Rail Cedar',
            height: 4,
            postType: 'post_cedar_2rail',
            postSpacing: 10,
            railType: 'rail_cedar_2rail',
            railCount: 2,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_3rail_cedar': {
            name: '4\' 3-Rail Cedar',
            height: 4,
            postType: 'post_cedar_3rail',
            postSpacing: 10,
            railType: 'rail_cedar_3rail',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_3rail_4x4': {
            name: '4\' 3-Rail 4"x4"',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            railType: 'rail_2x6x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x4x8',
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_3rail_6x6': {
            name: '4\' 3-Rail 6"x6"',
            height: 4,
            postType: 'post_6x6x8_pt',
            postSpacing: 7.5,
            railType: 'rail_2x6x16',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_4rail_4x4': {
            name: '4\' 4-Rail 4"x4"',
            height: 4,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            railType: 'rail_2x6x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x4x8',
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_4rail_6x6': {
            name: '4\' 4-Rail 6"x6"',
            height: 4,
            postType: 'post_6x6x8_pt',
            postSpacing: 7.5,
            railType: 'rail_2x6x16',
            railCount: 4,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5rail_4x4': {
            name: '5-Rail 4"x4"',
            height: 5,
            postType: 'post_4x4x8_pt',
            postSpacing: 7.5,
            railType: 'rail_2x6x16',
            railCount: 5,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x4x8',
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '5rail_6x6': {
            name: '5-Rail 6"x6"',
            height: 5,
            postType: 'post_6x6x8_pt',
            postSpacing: 7.5,
            railType: 'rail_2x6x16',
            railCount: 5,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            includedTrim: 'trim_1x6x8',
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_5_black_aluminum_flat': {
            name: '4.5\' Black Aluminum Flat Top',
            height: 4.5,
            postType: 'post_aluminum_line',
            postSpacing: 6,
            panelType: 'panel_aluminum_4_5',
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            isAluminum: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '6_vinyl_privacy': {
            name: '6\' Vinyl Privacy',
            height: 6,
            postType: 'post_5x5x8_vinyl',
            postSpacing: 8,
            panelType: 'panel_vinyl_6x8',
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            isVinyl: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_2rail_vinyl': {
            name: '4\' 2-Rail Vinyl',
            height: 4,
            postType: 'post_5x5x5_vinyl_2rail',
            postSpacing: 8,
            railType: 'rail_vinyl_8',
            railCount: 2,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            isVinyl: true,
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        },
        '4_3rail_vinyl': {
            name: '4\' 3-Rail Vinyl',
            height: 4,
            postType: 'post_5x5x7_vinyl_3rail',
            postSpacing: 8,
            railType: 'rail_vinyl_8',
            railCount: 3,
            concretePerPost: 1.25,
            allowsTrim: false,
            allowsCap: false,
            isVinyl: true,
            isRail: true,
            compatiblePostTops: ['top_4x4_metal', 'top_4x4_copper', 'top_6x6_metal', 'top_6x6_copper', 'top_5x5_vinyl', 'top_5x5_vinyl_decorative', 'top_5x5_vinyl_ranch'],
        }
    }
};